version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: "comments-db"
    ports:
      - ${DB_EXTERNAL_PORT}:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - go_comments
    volumes:
      - db_data:/var/lib/postgresql/data
  
  web:
    build: .
    container_name: "comments-api"
    environment:
      DB_USERNAME: "postgres"
      DB_PASSWORD: "postgres"
      DB_DB: "postgres"
      DB_HOST: "db"
      DB_TABLE: "postgres"
      DB_PORT: "5432"
      SSL_DISABLE: "disable"
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    networks:
      - go_comments

volumes:
  db_data:

networks:
  go_comments:
    driver: bridge